export enum ConnectionState {
    disconnected,
    disconnecting,
    connecting,
    connected,
    error,
}

export global Connection {
    in-out property <ConnectionState> state;

    out property <bool> is-disconnected: self.state == ConnectionState.disconnected;
    out property <bool> is-disconnecting: self.state == ConnectionState.disconnecting;
    out property <bool> is-connected: self.state == ConnectionState.connected;
    out property <bool> is-connecting: self.state == ConnectionState.connecting;
    out property <bool> is-error: self.state == ConnectionState.error;

    out property <bool> is-secure: self.state != ConnectionState.disconnected && self.state != ConnectionState.disconnecting;
}
