
import { Button, VerticalBox, Spinner } from "std-widgets.slint";
import { MullvadPalette } from "palette.slint";
import { State, ConnectionState } from "state.slint";
import { FeatureIndicators } from "feature-indicator.slint";
import { Route } from "route.slint";

component ConnectButton inherits Rectangle {
    in-out property <string> text: State.is-disconnected ? "Connect" : "Disconnect";
    callback clicked <=> touch.clicked;

    border-radius: 4px;
    height: 32px;

    function background-color() -> brush {
        if State.is-secure {
            if touch.pressed {
                return MullvadPalette.disconnected_red_dark;
            }
            if touch.has-hover {
                return MullvadPalette.disconnected_red_fade;
            }
            return MullvadPalette.disconnected_red;
        }
        
        if touch.pressed {
            return MullvadPalette.connected_green_dark;
        }
        if touch.has-hover {
            return MullvadPalette.connected_green_fade;
        }
        return MullvadPalette.connected_green;
    }

    background: background-color();

    Text {
        text: text;
        color: white;
        font-size: 11pt;
        font-weight: 550;
    }

    // This component will capture input events (e.g. mouse clicks)
    touch := TouchArea { }
}

component LocationButton inherits Rectangle {
    in-out property <string> text: "Switch Location";
    callback clicked <=> touch.clicked;

    border-radius: 4px;
    height: 32px;

    background: touch.pressed ? MullvadPalette.light_blue : touch.has-hover ? MullvadPalette.dim_blue : MullvadPalette.light_blue;
    Text {
        text: text;
        color: white;
        font-size: 11pt;
        font-weight: 550;
    }

    // This component will capture input events (e.g. mouse clicks)
    touch := TouchArea { }
}

component DashboardHeader {
    callback clicked <=> touch.clicked;

    property <string> state-text: {
        if State.is-connected {
            "CONNECTED"
        } else if State.is-disconnected {
            "DISCONNECTED"
        } else if State.is-disconnecting {
            "DISCONNECTING..."
        } else if State.is-connecting {
            "CONNECTING..."
        } else {
            "ERROR"
        }
    };

    touch := TouchArea { }

    VerticalLayout {
        state := HorizontalLayout {
            Text {
                text: root.state-text;
                color: State.is-connected ? MullvadPalette.connected_green : State.is-disconnected ? MullvadPalette.disconnected_red : white;
                font-size: 12pt;
                font-weight: 600;
            }

            Image {
                horizontal-alignment: right;
                source: @image-url("./images/icon-chevron-up.svg");
                height: 24px;
                width: 24px;
            }
        }

        location_txt := Text {
            text: State.connected-to-location;
            color: white;
            font-size: 12pt;
        }

        // Use a rectangle so we can clip the text when animating.
        Rectangle {
            clip: true;
            height: State.connected-to-hostname.is-empty ? 0 : txt.height;
            animate height {
                easing: ease-out;
                duration: 0.2s;
            }
            txt := Text {
                y: 0;
                x: 0;
                text: State.connected-to-hostname;
                color: #aaaaaa; // TODO: use the right value

            }
        }
    }
}

export component Dashboard {
    in-out property <length> anchor_y: 0px;
    callback on_connect <=> cb.clicked;

    Rectangle {
        border-radius: 16px;
        background: MullvadPalette.dark_blue_transparent;

        VerticalBox {
            alignment: end;
            padding: 16px;
            spacing: 16px;

            header := DashboardHeader {
                clicked => {
                    cb.clicked();
                }
            }

            FeatureIndicators { }

            location_button := LocationButton {
                clicked => { Route.select-location.show = true; }
            }

            cb := ConnectButton {
                clicked => {
                    State.connect-button();
                }
            }
        }
    }
}
