export global MullvadPalette {
    // TODO: align names and color values with figma
    in-out property <color> disconnected_red:      #e34039;
    in-out property <color> disconnected_red_fade: #bb3c3b;
    in-out property <color> disconnected_red_dark: #6a3540;
    in-out property <color> connected_green:       #44ad4d;
    in-out property <color> connected_green_fade:  #3b944b;
    in-out property <color> connected_green_dark:  #2a6148;
    in-out property <color> dark_blue:             #192e45;
    in-out property <color> darker_blue:           #192638; // used on the dashboard
    in-out property <color> dark_blue_transparent: #10182366;
    in-out property <color> light_blue:            #294d73;
    in-out property <color> lighter_blue:          #3e5f81;
    in-out property <color> lightest_blue:         #54718f;
    in-out property <color> dim_blue:              #224161;
    in-out property <color> dimmer_blue:           #1c344e;
}
