export global MullvadPalette {
    // TODO: align names and color values with figma
    in-out property <color> disconnected_red:      #e34039;
    in-out property <color> disconnected_red_dark: #c32019;
    in-out property <color> connected_green:       #44ad4d;
    in-out property <color> dark_blue:             #192e45;
    in-out property <color> dark_blue_transparent: #10182366;
    in-out property <color> light_blue:            #294d73;
    in-out property <color> dim_blue:              #224161;
}
