export struct Relay {
    hostname: string,
}

export struct City {
    name: string,
    code: string,
    relays: [Relay],
    latitude: angle,
    longitude: angle,
}

export struct Country {
    name: string,
    code: string,
    cities: [City],
}

export global RelayList {
    in-out property <[Country]> countries;
    in-out property <[Country]> filtered-countries: self.countries;
    callback search-location(string);
}
