import { Button } from "std-widgets.slint";
import { MainView } from "main-view.slint";
import { SettingsView, DaitaView, MultihopView, VpnSettingsView, AntiCensorshipView } from "settings.slint";
import { SelectLocationView } from "select-location.slint";
import { SplitTunnelingView, SplitTunneling } from "split-tunneling.slint";
import { View, Route } from "route.slint";

component RouterView {
    // Whether we should show or hide the window
    in property<bool> show: false;

    // Where to place the window if show=false
    in property<length> hide-at-x: 0px;
    in property<length> hide-at-y: 0px;

    // Animation duration
    in property<duration> duration: 0.5s;

    // TODO: hide @children behind if-statement once slint implements
    // https://github.com/slint-ui/slint/issues/6354
    visible: show || animation-timer.running;

    x: hide-at-x;
    y: hide-at-y;
    width: 100%;
    height: 100%;

    // init() => {
    //     self.x = show ? 0px : hide-at-x;
    //     self.y = show ? 0px : hide-at-y;
    // };

    changed show => {
        animation-timer.restart();
        animation-timer.start();
        self.x = show ? 0px : hide-at-x;
        self.y = show ? 0px : hide-at-y;
    }

    animation_timer := Timer {
        running: false;
        interval: duration;
        triggered() => {
            animation-timer.stop();
        };
    }

    animate x, y {
        duration: duration;
        easing: ease-in-out;
    }

    @children
}

export component Router {
    RouterView {
        show: true;
        MainView {}
    }

    RouterView {
        show: Route.settings.show;
        hide-at-y: root.height;
        SettingsView {}
    }

    RouterView {
        show: Route.daita.show;
        hide-at-x: root.width;
        DaitaView {}
    }

    RouterView {
        show: Route.multihop.show;
        hide-at-x: root.width;
        MultihopView {}
    }

    RouterView {
        show: Route.vpn-settings.show;
        hide-at-x: root.width;
        VpnSettingsView {}
    }

    RouterView {
        show: Route.anti-censorship.show;
        hide-at-x: root.width;
        AntiCensorshipView {}
    }

    RouterView {
        show: Route.split-tunneling.show; 
        hide-at-x: root.width;
        // HACK: load split tunneling app list when view is entered
        changed show => {
            if self.show {
                SplitTunneling.enter_view();
            }
        }
        SplitTunnelingView {}
    }

    RouterView {
        show: Route.select-location.show;
        hide-at-y: root.height;
        SelectLocationView {}
    }
}
