
import { HorizontalBox, VerticalBox, ScrollView } from "std-widgets.slint";
import { MullvadPalette } from "palette.slint";
import { RelayList, Country, City, Relay } from "relay-list.slint";
import { Route } from "route.slint";
import { State } from "state.slint";

component SelectLocationSection inherits HorizontalLayout {
    in property text <=> txt.text;

    height: 24px;
    spacing: 8px;

    txt := Text {
        text: "All locations";
        color: white;
        font-size: 14px;
        font-weight: 600;
    }

    VerticalLayout {
            height: parent.height;
            alignment: center;
        Rectangle {
            height: 1px;
            background: #fff4;
        }
    }
}

component RelayButton inherits VerticalLayout {
    in property <Country> country;
    in property <City> city;
    in property <Relay> relay;
    in property <bool> last-in-list: false;
    out property <bool> selected: State.selected-relay == relay.hostname;

    Rectangle {
        background: title_touch.pressed ? MullvadPalette.lightest_blue : title_touch.has-hover ? MullvadPalette.lighter_blue : MullvadPalette.dimmer_blue;
        height: 48px;
        border-bottom-left-radius: last-in-list ? 16px : 0;
        border-bottom-right-radius: last-in-list ? 16px : 0;

        if selected : Image {
            x: 12px;
            source: @image-url("./images/icon-checkmark.svg");
            colorize: MullvadPalette.connected_green;
        }

        Text {
            text: relay.hostname;
            color: selected ? MullvadPalette.connected_green : white;
            x: selected ? 48px : 12px;
            font-size: 14px;
        }

        title_touch := TouchArea {
            clicked => {
                State.select-relay(country, city, relay);
            }
        }
    }
}

component CityButton inherits VerticalLayout {
    in property <Country> country;
    in property <City> city;
    in property <bool> last-in-list: false;
    out property <bool> selected: State.selected-city == city.code && State.selected-relay == "";
    out property <bool> fold-out: false;
    out property <bool> round-bottom: !fold-out && last-in-list;

    HorizontalLayout {
        spacing: 2px;

        Rectangle {
            background: title_touch.pressed ? MullvadPalette.lightest_blue : title_touch.has-hover ? MullvadPalette.lighter_blue : MullvadPalette.dim_blue;
            height: 48px;
            border-bottom-left-radius: round-bottom ? 16px : 0;

            if selected : Image {
                x: 12px;
                source: @image-url("./images/icon-checkmark.svg");
                colorize: MullvadPalette.connected_green;
            }

            Text {
                text: city.name;
                color: selected ? MullvadPalette.connected_green : white;
                x: selected ? 48px : 12px;
                font-size: 14px;
            }

            title_touch := TouchArea {
                clicked => {
                    State.select-city(country, city);
                }
            }
        }

        Rectangle {
            background: fold_touch.pressed ? MullvadPalette.lightest_blue : fold_touch.has-hover ? MullvadPalette.lighter_blue : MullvadPalette.dim_blue;
            height: 48px;
            width: 48px;
            border-bottom-right-radius: round-bottom ? 16px : 0;

            Image {
                x: parent.width - self.width - 10px;
                height: 30px;
                opacity: 0.7;
                source: fold-out ? @image-url("./images/icon-chevron-up.svg")
                                 : @image-url("./images/icon-chevron-down.svg");
            }

            fold_touch := TouchArea {
                clicked => { fold-out = !fold-out; }
            }
        }
    }

    if fold-out: VerticalLayout {
        for relay[i] in city.relays: RelayButton {
            country: country;
            city: city;
            relay: relay;
            last-in-list: (i + 1) == city.relays.length;
        }
    }
}

component CountryButton inherits VerticalLayout {
    in property <Country> country;
    out property <bool> selected: State.selected-country == country.code && State.selected-city == "";
    out property <bool> fold-out: false;

    HorizontalLayout {
        spacing: 2px;

        Rectangle {
            background: title_touch.pressed ? MullvadPalette.lightest_blue : title_touch.has-hover ? MullvadPalette.lighter_blue : MullvadPalette.light_blue;
            height: 48px;
            border-top-left-radius: 16px;
            border-bottom-left-radius: fold-out ? 0 : 16px;

            if selected : Image {
                x: 12px;
                source: @image-url("./images/icon-checkmark.svg");
                colorize: MullvadPalette.connected_green;
            }

            Text {
                text: country.name;
                color: selected ? MullvadPalette.connected_green : white;
                x: selected ? 48px : 12px;
                font-size: 14px;
            }

            title_touch := TouchArea {
                clicked => {
                    State.select-country(country);
                }
            }
        }

        Rectangle {
            background: fold_touch.pressed ? MullvadPalette.lightest_blue : fold_touch.has-hover ? MullvadPalette.lighter_blue : MullvadPalette.light_blue;
            height: 48px;
            width: 48px;
            border-top-right-radius: 16px;
            border-bottom-right-radius: fold-out ? 0 : 16px;

            Image {
                x: parent.width - self.width - 10px;
                height: 30px;
                opacity: 0.7;
                source: fold-out ? @image-url("./images/icon-chevron-up.svg")
                                 : @image-url("./images/icon-chevron-down.svg");
            }

            fold_touch := TouchArea {
                clicked => { fold-out = !fold-out; }
            }
        }
    }

    if fold-out: VerticalLayout {
        for city[i] in country.cities: CityButton {
            country: country;
            city: city;
            last-in-list: (i + 1) == country.cities.length;
        }
    }
}

export component SelectLocationView inherits Rectangle {
    background: MullvadPalette.dark_blue;

    VerticalBox {
        padding: 0;
        HorizontalBox {
            alignment: space-between;

            Image {
                source: @image-url("./images/icon-chevron-down-circle.svg");
                height: 24px;
                opacity: input_close.has-hover ? 0.8 : 0.6;
                input_close := TouchArea {
                    clicked => {
                        Route.select-location.show = false;
                    }
                }
            }

            Text {
                color: white;
                text: "Select location";
                horizontal-alignment: center;
                font-size: 16px;
                font-weight: 600;
            }

            Image {
                source: @image-url("./images/icon-filter-circle.svg");
                height: 24px;
                opacity: input_filter.has-hover ? 0.8 : 0.6;
                input_filter := TouchArea {
                    clicked => {
                        // TODO filters
                    }
                }
            }
        }

        HorizontalBox {
            padding-left: 24px;
            padding-right: self.padding-left;
            Rectangle {
                height: 40px;
                border-radius: 4px;
                background: input.has-focus ? #fff : #fff2;
                input := TextInput {
                    color: self.has-focus ? #000 : #fff9;
                    x: 40px;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    font-size: 15px;
                }

                Image {
                    x: 8px;
                    source: @image-url("./images/icon-search.svg");
                    height: 28px;
                    colorize: input.has-focus ? #000000 : #fffa;
                }
            }
        }

        ScrollView {
            vertical-scrollbar-policy: always-off;
            horizontal-scrollbar-policy: always-off;
            VerticalLayout {
                padding: 16px;
                spacing: 4px;

                SelectLocationSection {
                    text: "Latest";
                }

                Rectangle {
                    height: 16px;
                }

                SelectLocationSection {
                    text: "Custom lists";
                }

                Rectangle {
                    height: 16px;
                }

                SelectLocationSection {
                    text: "All locations";
                }

                for country in RelayList.countries: CountryButton {
                    country: country;
                }
            }
        }
    }
}
